version: 2.1
jobs:
  build:
    docker:
      - image: gcc:8
        environment:
          - targets="DIR-878-5.0 MI-R3G"
          - toolchain_url=https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
    parallelism: 1
    steps:
      - run: cat /etc/apt/sources.list
      - run: |
          echo "deb http://deb.debian.org/debian/ buster main non-free contrib
          deb-src http://deb.debian.org/debian/ buster main non-free contrib
          deb http://security.debian.org/debian-security buster/updates main non-free contrib
          deb-src http://security.debian.org/debian-security buster/updates main non-free contrib
          deb http://deb.debian.org/debian/ buster-updates main non-free contrib
          deb-src http://deb.debian.org/debian/ buster-updates main non-free contrib
          deb http://deb.debian.org/debian/ buster-backports main non-free contrib
          deb-src http://deb.debian.org/debian/ buster-backports main non-free contrib
          " | tee /etc/apt/sources.list
      - run: cat /etc/apt/sources.list
      - run: apt-get update
      - run: apt-get install -y --no-install-recommends fakeroot, p7zip-full, libtool-bin, gperf, texinfo, python-docutils, autopoint
      - run: rm -rf ./rt-n56u/toolchain-mipsel/ && mkdir -p ./rt-n56u/toolchain-mipsel/toolchain-3.4.x && mkdir -p ./images
      - run: wget $toolchain_url && tar -xf mipsel-linux-uclibc.tar.xz -C ./rt-n56u/toolchain-mipsel/toolchain-3.4.x
      - run: ls -Alh /opt/rt-n56u && cd /opt/rt-n56u/trunk/
      - run: for m in $targets; do fakeroot ./build_firmware_nohup $m && cp -f images/*.trx /opt/images/$m.trx; ./clear_tree_simple >/dev/null 2>&1; done
      - run: GIT_VERSION=`git rev-parse --short=7 HEAD 2>/dev/null` && [ -n "$GIT_VERSION" ] && image_name=images_mt7621_$GIT_VERSION || image_name=images_mt7621
      - run: cd /opt/images; du -k *; md5sum *.trx |tee md5sum.txt ; 7z a -mx=9 ${image_name}.7z ./*
      - run: "curl -m 180 -H 'Max-Days: 3' --upload-file ./${image_name}.7z https://transfer.sh/${image_name}.7z ; echo"
      - run: curl -v -F file=./${image_name}.7z https://file.io

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
