version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:bionic
        environment:
          targets: DIR-878-5.0 MI-R3G
          image_name: images_mt7621
          toolchain_url: https://github.com/cxjava/rt-n56u/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
          toolchain_url_backup: https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
    parallelism: 1
    working_directory: /opt
    steps:
      - run:
          name: 更新并安装依赖软件
          command: apt-get update && apt-get install -y --no-install-recommends module-init-tools tree wget ca-certificates git git-core libssl-dev automake autopoint bison build-essential cmake cpio curl fakeroot flex gawk gettext git gperf help2man libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libtool-bin nano p7zip-full pkg-config python-docutils texinfo unzip xxd zlib1g-dev
      - run:
          name: 克隆仓库
          working_directory: /opt
          command: |
            git clone --depth=1 https://github.com/cxjava/rt-n56u.git
            mkdir -p ./images
      - run:
          name: 下载编译好的toolchain
          working_directory: /opt/rt-n56u
          command: |
            tree . -h -L 3
            rm -rf ./toolchain-mipsel/ && mkdir -p ./toolchain-mipsel
            wget $toolchain_url && tar -xf mipsel-linux-uclibc.tar.xz -C ./toolchain-mipsel
            tree . -h -L 4
      - run:
          name: 编译
          working_directory: /opt/rt-n56u/trunk
          command: |
            for m in $targets; do
              fakeroot ./build_firmware_nohup $m && cp -f images/*.trx /opt/images/$m.trx
              ./clear_tree_simple >/dev/null 2>&1
            done
      - run:
          name: 打包
          working_directory: /opt/images
          command: |
            du -k *
            md5sum *.trx |tee md5sum.txt
            7z a -mx=9 ${image_name}.7z ./*
            tree . -h
            curl -F file=@/opt/images/${image_name}.7z https://file.io
            curl -F file=@/opt/images/${image_name}.7z https://0x0.st
      - store_artifacts:
          path: /opt/images
          destination: MI-R3G.trx
      - store_artifacts:
          path: /opt/images
          destination: DIR-878-5.0.trx
      - store_artifacts:
          path: /opt/images
workflows:
  version: 2.1
  build-workflow:
    jobs:
      - build
